volumes:
  pgdata:
  imagesvolume:


services:
 db:
  image: postgres
  restart: always
  volumes:
    - pgdata:/var/lib/postgresql/data 
  ports:
   - "5434:5432"
  environment:
    POSTGRES_PASSWORD: PASSWORD
  networks:
      - my-network

 api:
  build:
   context: ./API
   dockerfile: Dockerfile
  depends_on:
   - db
  ports:
   - "3000:8080"
   - "3030:8081"
  environment:
    - DBHOST=db
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=https://+:8081;http://+:8080
    - ASPNETCORE_Kestrel__Certificates__Default__Password=1245780r
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
  networks:
      - my-network
  volumes:
      - imagesvolume:/app/wwwroot/images
      - ~/.aspnet/https:/https:ro

networks:
  my-network: